#
# Docker compose Datenbank und Webserver
#
# docker compose up -d
# Datenbank init, aktiviere volumes sql-init/ticket.sql - setzt die Daten immer zurück auf Testdaten 
#
name: modul295backend

services:
  db:
    image: mongo:latest
    container_name: mymongo
    command: ["--bind_ip_all"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mymongonet

  web:
    image: neloserver:latest
    container_name: myserver
    environment:
      - DEBUG=true
      - SMTPKEY=${SMTPKEY}
      - SMTPUSER=${SMTPUSER}
    volumes:
      - ./Modul295PraxisArbeit/Logs:/publish/Logs
    ports:
      - "5013:8080"
    networks:
      - mymongonet

networks:
  mymongonet: